<?php

/** @var \SM\SU\Block\Brands $block */
$collection = $block->getBrandCollection();

$params = $this->getRequest()->getParams();
$helper = $this->helper('SM\SU\Helper\Data');

if ($this->getConfig('list_page_settings/small_image_width') != '') {
    $width = $this->getConfig('list_page_settings/small_image_width');
} else {
    $width = 140;
}
if ($this->getConfig('list_page_settings/small_image_height') != '') {
    $height = $this->getConfig('list_page_settings/small_image_height');
} else {
    $height = 30;
}
?>


<div class="shop-by-brand">
    <?php echo $block->getChildHtml('brand_filter_by_character'); ?>
    <div class="all-brands">
        <?php $flagDigit = false; ?>
        <?php if ($collection->count()): ?>
            <?php $total = $collection->getSize(); ?>
            <div class="content">
                <ul class="brand-list">
                    <?php $letter =null ?>
                    <?php foreach ($collection as $brand): ?>
                            <?php  if( $letter != strtoupper(substr($brand->getName(), 0, 1))):?>
                            <?php  $letter = strtoupper(substr($brand->getName(), 0, 1)); ?>
                            <?= '<hr />'; ?>
                            <?= $letter; ?>

                            <?php endif; ?>
                                <li class="item">
                                    <div class="brand-content">
                                        <div class="brand-image">
                                            <a title="<?php echo $brand->getName(); ?>"
                                               href="<?php echo $brand->getUrl(); ?>">
                                                <img style="height: <?= $height; ?>px; width: <?= $width; ?>px " class="brand-small-image"
                                                     alt="<?php echo $brand->getName(); ?>"
                                                     src="<?php echo $brand->getThumbnailUrl(); ?>">
                                            </a>
                                        </div>

                                    </div>
                                </li>
                    <?php endforeach; ?>
                    <li class="clear"></li>
                </ul>
            </div>

            <?php if ($block->getPagerHtml()): ?>
                <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
            <?php endif ?>
        <?php else: ?>
            <div class="message">
                <div><?php echo __('Have no brands.') ?></div>
            </div>
        <?php endif; ?>
    </div>
</div>

