<?php
$helper = $this->helper('SM\SU\Helper\Data');
$params = $this->getRequest()->getParams();
//die($params['char']);
?>
<div class="characters">
    <ul class="characters-filter">
            <?php foreach (range('A', 'Z') as $char): ?>
                <li class="<?php if (isset($params['char']) && $params['char'] === $char) { echo 'active';} else echo '';?>"><a href="<?php echo $helper->getBrandUrl() . '?char=' . $char; ?>"><?php echo $char; ?></a></li>
            <?php endforeach; ?>
    </ul>
    <div class="view-all">
        <a title="<?php echo __('View All'); ?>" href="<?php echo $helper->getBrandUrl(); ?>"><?php echo __('View All'); ?></a>
    </div>
	<div class="clear"></div>
</div>
<script>
</script>
