<?php


/** @var Menu $block */

use SM\SU\Block\Category\Menu;

$categorys = $block->getCollections();
?>

    <li class="level0 category-item level-top parent ui-menu-item" role="presentation">
        <a href="<?= /* @noEscape */
        $block->getUrlBrand() ?>" class="level-top ui-corner-all" aria-haspopup="true" id="ui-id-6" tabindex="-1"
           role="menuitem">
            <?php if (sizeof($categorys)) : ?>
                <span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span>
            <?php endif; ?>
            <span><?= /* @noEscape */
                $block->getBrandHomePageTitle() ?></span>
        </a>
        <?php if (sizeof($categorys)) : ?>
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu"
                aria-expanded="false" style="display: none; top: 47px; left: -0.15625px;" aria-hidden="true">
                <?php foreach ($categorys as $category) : ?>
                    <li class="level 0 category-item ui-menu-item" role="presentation">
                        <a href='<?= $category->getUrl(); ?>' class="ui-corner-all" tabindex="-1" role="menuitem">
                            <span><?php echo $category->getName();?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </li>

<?php



