<?php
/**
 * @ SM/
 */
$_brandCollection = $block->getCollection();
?>
<?php if ( $_brandCollection->count() ){ ?>
    <?php $total = $_brandCollection->getSize(); ?>
    <div class="brandlist">
        <div class="block-content">
            <?php foreach ($_brandCollection as $_brand) { ?>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="border:2px solid green; padding: 15px" ">
                    <div class="brand-item">
                        <div class="brand-image">
                            <?php $image = $_brand->getThumbnailUrl();?>
                            <a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>">
                                <?php if($image){ ?>
                              <img src="<?php echo $_brand->getThumbnailUrl(); ?>" alt="<?php echo $_brand->getName(); ?>" width="200" height="200"/>
                                <?php } ?>
                                <?= $_brand->getName(); ?>
                            </a>

                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
        <?php if($html = $block->getChildHtml('toolbar')){ ?>
            <div class="brand-toolbar  toolbar toolbar-products">
                <?php echo $block->getChildHtml('toolbar'); ?>
            </div>
        <?php } ?>
    </div>
<?php }else{ ?>
    <div class="message info empty"><div><?php echo __('We can\'t find brand matching the selection.'); ?></div></div>
<?php } ?>
